#!/usr/bin/env python3
"""
DAM Model Serialization Script

This script trains and serializes DAM price forecast models.
Models are saved to the prediction-service/models directory.

Prerequisites:
1. Training data in train_data/dam_features.csv (generated by DAM_feature_extraction.ipynb)
2. Required packages: xgboost, lightgbm, catboost, scikit-learn, pandas

Usage:
    python serialize_dam_models.py --input /path/to/dam_features.csv --output ../models/dam/
"""

import argparse
import os
import json
import joblib
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path

# ML frameworks
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error


def load_features(filepath: str) -> pd.DataFrame:
    """Load feature dataset."""
    df = pd.read_csv(filepath)
    if 'dt' in df.columns:
        df['dt'] = pd.to_datetime(df['dt'])
    return df


def prepare_data(df: pd.DataFrame, train_end: str = "2024-12-31"):
    """
    Prepare training and test data.

    Args:
        df: Feature DataFrame
        train_end: End date for training data

    Returns:
        X_train, X_test, y_train, y_test
    """
    # Feature columns (exclude target and metadata)
    exclude_cols = ['dt', 'hour', 'target', 'pred', 'timestamp', 'date']
    feature_cols = [c for c in df.columns if c not in exclude_cols]

    # Split by date
    train_mask = df['dt'] <= train_end
    train_df = df[train_mask]
    test_df = df[~train_mask]

    X_train = train_df[feature_cols]
    y_train = train_df['target']
    X_test = test_df[feature_cols]
    y_test = test_df['target']

    return X_train, X_test, y_train, y_test, feature_cols


def train_xgboost(X_train, y_train, hour: int = None):
    """Train XGBoost model."""
    model = XGBRegressor(
        n_estimators=1000,
        max_depth=6,
        learning_rate=0.01,
        objective='reg:absoluteerror',
        tree_method='hist',
        random_state=42,
        n_jobs=-1
    )
    model.fit(X_train, y_train)
    return model


def train_lightgbm(X_train, y_train, hour: int = None):
    """Train LightGBM model."""
    model = LGBMRegressor(
        n_estimators=1000,
        num_leaves=31,
        max_depth=8,
        learning_rate=0.01,
        objective='mae',
        random_state=42,
        n_jobs=-1,
        verbose=-1
    )
    model.fit(X_train, y_train)
    return model


def train_catboost(X_train, y_train, cat_features=None, hour: int = None):
    """Train CatBoost model."""
    model = CatBoostRegressor(
        iterations=2000,
        depth=6,
        learning_rate=0.2,
        loss_function='MAE',
        random_state=42,
        verbose=False
    )
    model.fit(X_train, y_train, cat_features=cat_features)
    return model


def main():
    parser = argparse.ArgumentParser(description="Train and serialize DAM forecast models")
    parser.add_argument("--input", required=True, help="Path to dam_features.csv")
    parser.add_argument("--output", default="../models/dam", help="Output directory for models")
    parser.add_argument("--train-end", default="2024-12-31", help="End date for training data")
    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading features from {args.input}")
    df = load_features(args.input)
    print(f"Loaded {len(df)} records")

    # Prepare data
    X_train, X_test, y_train, y_test, feature_cols = prepare_data(df, args.train_end)
    print(f"Training: {len(X_train)}, Testing: {len(X_test)}")

    # Identify categorical features
    cat_features = ['hour', 'day_of_week', 'month', 'is_weekend', 'is_peak_hour', 'is_summer']
    cat_indices = [i for i, c in enumerate(feature_cols) if c in cat_features]

    results = {}

    # Train XGBoost
    print("\nTraining XGBoost...")
    xgb_model = train_xgboost(X_train, y_train)
    xgb_pred = xgb_model.predict(X_test)
    xgb_mae = mean_absolute_error(y_test, xgb_pred)
    print(f"  MAE: {xgb_mae:.2f}")
    joblib.dump(xgb_model, output_dir / "xgboost_dam.joblib")
    results['xgboost'] = {'mae': xgb_mae}

    # Train LightGBM
    print("\nTraining LightGBM...")
    lgb_model = train_lightgbm(X_train, y_train)
    lgb_pred = lgb_model.predict(X_test)
    lgb_mae = mean_absolute_error(y_test, lgb_pred)
    print(f"  MAE: {lgb_mae:.2f}")
    joblib.dump(lgb_model, output_dir / "lightgbm_dam.joblib")
    results['lightgbm'] = {'mae': lgb_mae}

    # Train CatBoost
    print("\nTraining CatBoost...")
    cat_model = train_catboost(X_train, y_train, cat_features=cat_indices)
    cat_pred = cat_model.predict(X_test)
    cat_mae = mean_absolute_error(y_test, cat_pred)
    print(f"  MAE: {cat_mae:.2f}")
    cat_model.save_model(str(output_dir / "catboost_dam.cbm"))
    results['catboost'] = {'mae': cat_mae}

    # Ensemble prediction
    ensemble_pred = (xgb_pred + lgb_pred + cat_pred) / 3
    ensemble_mae = mean_absolute_error(y_test, ensemble_pred)
    print(f"\nEnsemble MAE: {ensemble_mae:.2f}")
    results['ensemble'] = {'mae': ensemble_mae}

    # Save metadata
    metadata = {
        'trained_at': datetime.utcnow().isoformat(),
        'training_samples': len(X_train),
        'test_samples': len(X_test),
        'feature_columns': feature_cols,
        'results': results
    }
    with open(output_dir / "metadata.json", 'w') as f:
        json.dump(metadata, f, indent=2)

    print(f"\nModels saved to {output_dir}")
    print("Files:")
    for f in output_dir.iterdir():
        print(f"  - {f.name}")


if __name__ == "__main__":
    main()
